### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [taylorn16/firehoseproject-splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by taylorn16** [comment]
Ken,

I added the device-width meta tag. Used to using a boilerplate that includes that tag for me, so I overlooked it! I should be more careful. Things look good on my smartphone now!

**Comment by kenmazaika** [comment]
Thumbs up!  Great work getting the viewport meta tag!
